from pathlib import Path
import os,sys,json,subprocess,hashlib,datetime,uuid
Q=Path('/workspace/work/gpc-no-data61');R='/workspace/g-pc-health-check';L='/workspace/gpc-no-data61';S='/workspace/work/gpc-audit60/.agents/skills/continuous-development-cycle/scripts';sys.path.insert(0,S)
from git_object_integrity import git_object_environment
from git_document_store import GitDocumentStore,canonical
from git_lease_store import GitLeaseStore
from git_remote_identity import isolated_remote_args
REF='refs/heads/cdc/gpc-native-fresh-recovery-evidence-20261009';SOURCE='refs/heads/design/0.17.0-security-posture';ID='sha256:e9c5798b2e5857d11563b10845ae993ed5b0e7b040ffd6611bdbd1a36aad08d3';KEY='no_data61_implementation_handoff';env=git_object_environment(GIT_AUTHOR_NAME='GPC artifact evidence',GIT_AUTHOR_EMAIL='evidence@example.invalid',GIT_COMMITTER_NAME='GPC artifact evidence',GIT_COMMITTER_EMAIL='evidence@example.invalid',GIT_TERMINAL_PROMPT='0')
def git(*args,data=None,repo=R,extra=None,timeout=60):
 e=dict(env);e.update(extra or {});p=subprocess.run(['git','-c','advice.graftFileDeprecated=false','-C',repo,*args],input=data,capture_output=True,env=e,timeout=timeout)
 if p.returncode:raise RuntimeError('read/local Git failed '+str(args[:2])+': '+p.stderr.decode(errors='replace'))
 return p.stdout

def durable(path,value):
 raw=json.dumps(value,indent=2,ensure_ascii=False).encode()+b'\n';tmp=path.with_suffix('.tmp');
 with open(tmp,'wb') as f:f.write(raw);f.flush();os.fsync(f.fileno())
 os.replace(tmp,path);fd=os.open(path.parent,os.O_DIRECTORY);os.fsync(fd);os.close(fd)
def text(*args,**kwargs):return git(*args,**kwargs).decode().strip()
def hashblob(raw):return text('hash-object','-w','--stdin',data=raw)
def tree(files,name):
 idx=Q/(name+'.index');assert not idx.exists();extra={'GIT_INDEX_FILE':str(idx)};git('read-tree','--empty',extra=extra);lines=b''.join(('100644 '+oid+'\t'+path+'\n').encode() for path,oid in sorted(files.items()));git('update-index','--index-info',data=lines,extra=extra);return text('write-tree',extra=extra)

class RawLeaseReadback:
    # Evidence-only read. CDC21 validation rejected the current administrative
    # retirement field; do not normalize or mutate the authoritative record.
    def read(self):
        ref = 'refs/heads/cdc/coordination'
        config, endpoint = isolated_remote_args(R, 'origin', ID)
        revision = text('ls-remote', '--refs', 'origin', ref).split()[0]
        git(*config, 'fetch', '--no-tags', '--no-write-fetch-head', '--refmap=', endpoint, ref)
        return revision, json.loads(git('show', revision + ':lease.json'))

verification=json.loads((Q/'verification.json').read_text());candidate=verification['candidate'];assert text('rev-parse','HEAD',repo=L)==candidate and text('status','--porcelain',repo=L)=='';assert text('rev-parse',candidate+'^',repo=L)==verification['parent'];assert text('rev-parse',candidate+':.agents/skills/continuous-development-cycle',repo=L)=='9c45d98c3254e9658d452c505d8c97698e3fc9a7'
assert text('hash-object','-t','commit','--stdin',data=(Q/'candidate-commit.raw').read_bytes(),repo=L)==candidate
store=GitDocumentStore(R,'origin',REF,ID,protected_refs=[SOURCE,'refs/heads/cdc/coordination']);old,doc=store.read();assert KEY not in doc,'existing evidence: reconcile, never duplicate';before=json.loads(json.dumps(doc));lease_store=RawLeaseReadback();coord,lease=lease_store.read();source=text('ls-remote','--refs','origin',SOURCE).split()[0];assert len(source)==40;assert lease['generation'] >= 31 and lease['owner_id'] is None and lease['external_guard'] is None
assert text('rev-parse','HEAD')=='38b00741642cf11afb879767ebd41901daf5d9bb' and text('status','--porcelain')==''
files={};prefix='artifact-handoff/no-data61-'+candidate[:8];raw=(Q/verification['binary_name']).read_bytes();assert hashlib.sha256(raw).hexdigest()==verification['sha256'];chunks=[]
for i in range(0,len(raw),4*1024*1024):
 chunk=raw[i:i+4*1024*1024];path=prefix+f'/chunk-{len(chunks):03d}.bin';oid=hashblob(chunk);files[path]=oid;chunks.append(dict(index=len(chunks),path=path,bytes=len(chunk),sha256=hashlib.sha256(chunk).hexdigest(),blob_oid=oid))
paths=text('diff','--name-only',verification['parent'],candidate,repo=L).splitlines();changed=[]
for path in paths:
 b=git('show',candidate+':'+path,repo=L);oid=hashblob(b);out=prefix+'/source/files/'+path;files[out]=oid;changed.append(dict(path=path,bytes=len(b),sha256=hashlib.sha256(b).hexdigest(),git_blob=oid,artifact_path=out))
for local,out in [('candidate.bundle','source/candidate.bundle'),('candidate.patch','source/candidate.patch'),('candidate-commit.raw','source/candidate-commit.raw'),('verification.json','verification.json'),(verification['binary_name']+'.sha256','checksum.sha256'),('publish-receipt.json','build/publish-receipt.json'),('publish.stdout','build/publish.stdout'),('publish.stderr','build/publish.stderr'),('compile.log','build/compile.log'),('RED.log','tests/RED.log'),('GREEN.log','tests/GREEN.log'),('final-regressions.log','tests/final-regressions.log'),('baseline-regressions.log','tests/baseline-regressions.log'),('resource-verification.json','tests/resource-verification.json'),('brand-provenance.json','build/brand-provenance.json'),('restore-brand.py','build/restore-brand.py'),('harness/Harness.csproj','tests/harness/Harness.csproj'),('harness/ExtractedDeclarations.cs','tests/harness/ExtractedDeclarations.cs'),('harness/declaration-provenance.json','tests/harness/declaration-provenance.json'),('harness/Program.cs','tests/harness/Program.cs'),('handoff.py','handoff-helper.py'),('verify-artifact.py','build/verify-artifact.py'),('publish-local.py','build/publish-local.py')]:files[prefix+'/'+out]=hashblob((Q/local).read_bytes())
manifest=dict(**{**verification,'schema':'gpc-raw-artifact-handoff/v1'},chunks=chunks,changed_files=changed,source_bundle=prefix+'/source/candidate.bundle',source_bundle_sha256=hashlib.sha256((Q/'candidate.bundle').read_bytes()).hexdigest(),source_patch=prefix+'/source/candidate.patch',source_patch_sha256=hashlib.sha256((Q/'candidate.patch').read_bytes()).hexdigest(),complete_history_bundle=True,core='CDC2.12.1 unchanged',SPEC='PENDING Root62',QUALITY='PENDING Root63');manifest_raw=(json.dumps(manifest,indent=2)+'\n').encode();mp=prefix+'/manifest.json';files[mp]=hashblob(manifest_raw);(Q/'manifest.json').write_bytes(manifest_raw)
artifact_tree=tree(files,'artifact');artifact=text('commit-tree',artifact_tree,data=b'Immutable local no-data61 EXE/source/test artifact bytes\n');assert store.read()==(old,before),'changed evidence ref before proposal'
record=dict(schema='gpc-no-data61-implementation-handoff/v1',attempt='gpc-no-data61-20261010',admission='924a4790c19b02a23e7711f83d4a0eb8e39a9c53',token='7420ea81-6b02-4cba-b46e-2d7bab8afded',candidate=candidate,root_tree=verification['tree'],sole_parent=verification['parent'],local_branch='codex/local-no-data61',local_worktree=L,artifact_commit=artifact,artifact_tree=artifact_tree,manifest_path=mp,manifest_blob=files[mp],manifest_sha256=hashlib.sha256(manifest_raw).hexdigest(),binary={k:verification[k] for k in ['binary_name','bytes','sha256','PE','FileVersion','InformationalVersion','bundle_entries']},bounded_diff=dict(files=len(paths),paths=paths),tests=dict(behavior_RED='1/10 passed, exit1; compiler setup failures excluded from RED',behavior_GREEN='10/10 passed, exit0',final_behavior='10/10',security_evaluator='9/9',existing_guidance='12/19 on both exact parent and candidate in Linux portable harness; same seven failures, no waiver',triage_regression='exit1 on both exact parent and candidate',resources='32 XML files; every previous resource value preserved',diff_check='exit0',Windows_crossbuild='SDK8.0.425, warnings-as-errors, exit0 / 0 warnings / 0 errors',crosspublish='exit0, complete self-contained win-x64 singlefile'),requested_source_in_admission='7aaefdebca68eed64c8e92d7dfff7384f0a3c800',source_admission_mismatch=(source!='7aaefdebca68eed64c8e92d7dfff7384f0a3c800'),source_before=source,coord_before=coord,lease_before=lease,lease_validation=dict(canonical_CDC21='REJECTED lease fields mismatch: current administrative submission_retirements field',raw_readback_only=True,no_lease_authority_or_mutation=True),original_CI6_outcome='UNKNOWN retained',no_source_publication=True,no_CI_or_children=True,Windows_runtime='NOT_RUN',manual_UI_UAC_DPI_RDP_Huawei_Win11='NOT_RUN',independent_SPEC_QUALITY='PENDING',artifact_only_not_release=True,build_receipt=json.loads((Q/'publish-receipt.json').read_text()),brand_provenance=json.loads((Q/'brand-provenance.json').read_text()),prepared_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),duration_basis='Contract file materialization through handoff; physical provider timing unknown',contract_materialized_at_utc=datetime.datetime.fromtimestamp((Q/'contract.txt').stat().st_mtime,datetime.timezone.utc).isoformat())
doc[KEY]=record;encoded=canonical(doc).encode();blob=hashblob(encoded);final_tree=tree({'document.json':blob},'document');proposal=text('commit-tree',final_tree,'-p',old,'-p',artifact,data=('Evidence-only no-data61 handoff '+str(uuid.uuid4())+'\n').encode());assert text('ls-tree','--name-only',proposal)=='document.json';git('merge-base','--is-ancestor',old,proposal);assert store.read()==(old,before) and lease_store.read()==(coord,lease) and text('ls-remote','--refs','origin',SOURCE).split()[0]==source
config,endpoint=isolated_remote_args(R,'origin',ID);argv=['git','-c','advice.graftFileDeprecated=false','-C',R,*config,'push','--porcelain','--force-with-lease='+REF+':'+old,endpoint,proposal+':'+REF];intent=dict(schema='gpc-evidence-only-CAS/v1',expected_old=old,proposal=proposal,artifact_commit=artifact,ref=REF,argv=argv,source=source,coordination=coord,one_send=True,history_rewrite=False,send_state='consumed_before_send',at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat());assert not (Q/'handoff-send-intent.json').exists();durable(Q/'handoff-send-intent.json',intent)
try:
 p=subprocess.run(argv,env=env,capture_output=True,timeout=180);durable(Q/'handoff-send-result.json',dict(returncode=p.returncode,stdout=p.stdout.decode(errors='replace'),stderr=p.stderr.decode(errors='replace'),finished_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat()))
except subprocess.TimeoutExpired as ex:
 durable(Q/'handoff-send-result.json',dict(returncode=None,outcome='UNKNOWN timeout, no replay',stdout=(ex.stdout or b'').decode(errors='replace'),stderr=(ex.stderr or b'').decode(errors='replace')));raise
assert p.returncode==0,'Transport failed: preserve intent/result, do not replay'
assert store.read()==(proposal,doc);assert store.read_revision(old)==before;assert text('ls-tree','--name-only',proposal)=='document.json';after_coord,after_lease=lease_store.read();assert after_lease==lease and after_coord==coord;assert text('ls-remote','--refs','origin',SOURCE).split()[0]==source;assert text('status','--porcelain')=='' and text('status','--porcelain',repo=L)==''
receipt=dict(ref=REF,canonical_commit=proposal,canonical_blob=blob,key=KEY,artifact_commit=artifact,manifest_path=mp,manifest_blob=files[mp],candidate=candidate,root_tree=verification['tree'],binary_sha256=verification['sha256'],bytes=verification['bytes'],chunks=len(chunks),source_unchanged=source,coordination_unchanged=coord,lease_unchanged=True,canonical_tree_only_document=True,old_keys_and_readback_preserved=True,finished_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),duration_seconds=(datetime.datetime.now(datetime.timezone.utc).timestamp()-(Q/'contract.txt').stat().st_mtime),push_exit=p.returncode,Windows_runtime='NOT_RUN',original_CI6_outcome='UNKNOWN');durable(Q/'final-receipt.json',receipt);print(json.dumps(receipt,indent=2))
