import sys,pathlib,json,subprocess,datetime,importlib.util,re,os
driver='/workspace/work/released-2.12.1-adoption/src/continuous-development-cycle/scripts';sys.path.insert(0,driver)
import managed_host_bridge as bridge,operation_intent as op,execution_lease_v2 as v2
from git_document_store import GitDocumentStore
from git_remote_identity import remote_identity
name=sys.argv[1];allroot=pathlib.Path('/workspace/work/adopt2121-20261008');root=allroot/(name+'-adapter');req=json.loads((root/'start-request.json').read_text());h=json.loads((root/'start-receipt.json').read_text());proof=json.loads((root/'preparation.json').read_text());repo=req['repo_root'];rid=remote_identity(repo,'origin')
def now():return datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
def git(*a):
 p=subprocess.run(['git',*a],cwd=repo,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
 if p.returncode:
  err=re.sub(r'https://[^/@\s]+@','https://[redacted]@',p.stderr);err=re.sub(r'(?:gh[pousr]_[A-Za-z0-9]+|github_pat_[A-Za-z0-9_]+)','[redacted]',err)
  (root/'native-git-last-error.json').write_text(json.dumps({'argv':['git',*a],'exit_code':p.returncode,'stderr':err},indent=2)+'\n');raise RuntimeError('native Git failed; sanitized stderr saved')
 return p.stdout.strip()
session,runtime,ls=bridge._recover_session(req['handle_root'],h['handle_id']);o=runtime.observe(req['task_id'],req['attempt_id']);assert o['status']=='awaiting_release' and o['pending_terminal_status']=='succeeded';bridge._renew_for_result(session,ls,o);head,paths,_=bridge._result(session,runtime);assert head==proof['candidate']
assembly_ref='refs/heads/cdc/adopt2121-'+name+'-assembly-20261008'
if name!='fleet':
 es=GitDocumentStore(repo,'origin',assembly_ref,rid);er,old=es.read();assert er is None or old==proof['assembly_record'];er=es.compare_and_swap(None,proof['assembly_record']) if er is None else er;assert es.read()==(er,proof['assembly_record']);(root/'assembly-authority.json').write_text(json.dumps({'schema':'migration-assembly-authority/v1','store_ref':assembly_ref,'store_id':rid,'revision':er,'transaction_id':proof['assembly_record']['transaction_id'],'manifest_digest':proof['assembly_record']['manifest_digest']},indent=2)+'\n')
import hashlib
artifact=(allroot/'ordered-review-acceptance.json').read_bytes();assert hashlib.sha256(artifact).hexdigest()=='c279e9a278e2d4b05069cf5a47d58044674f63c19b071d5122655ee3ffce850d'
report={'schema':'cdc-independent-review-journal/v1','review_kind':'ORDERED_ACCEPTANCE','source':'actual owner-uploaded ordered-review-acceptance.json; bytes copied, not reconstructed','artifact_path':'ordered-review-acceptance.json','artifact_utf8_bytes':len(artifact),'artifact_sha256':hashlib.sha256(artifact).hexdigest(),'status':'ACCEPTED_SPEC_THEN_QUALITY','scope':'four immutable adoption candidates; does not authorize live effects','actual_source_base_unchanged':proof['base']}
rows=git('log','--all','--format=%an%x09%ae').splitlines();author_name,author_email=next(row.split('\t',1) for row in rows if '\t' in row and row.split('\t',1)[1].endswith('@users.noreply.github.com'));os.environ.update(GIT_AUTHOR_NAME=author_name,GIT_AUTHOR_EMAIL=author_email,GIT_COMMITTER_NAME=author_name,GIT_COMMITTER_EMAIL=author_email,GIT_TERMINAL_PROMPT='0')
raw=(json.dumps(report,indent=2)+'\n').encode();(root/'ordered-review-journal-document.json').write_bytes(raw)
entries=[]
for filename,data in [('document.json',raw),('ordered-review-acceptance.json',artifact),('publication-adapter.py',pathlib.Path(__file__).read_bytes())]:
 blob=subprocess.check_output(['git','hash-object','-w','--stdin'],input=data,cwd=repo).decode().strip();entries.append('100644 blob '+blob+'\t'+filename+'\n')
tree=subprocess.check_output(['git','mktree'],input=''.join(entries).encode(),cwd=repo).decode().strip();head=subprocess.check_output(['git','commit-tree',tree,'-m','Store actual independent QUALITY artifact [skip ci]'],cwd=repo).decode().strip()
candidate_ref='refs/heads/cdc/adopt2121-'+name+'-ordered-review-journal-20261008';assert not git('ls-remote','origin',candidate_ref)
binding={'repository':req['lease_repository'],'candidate_sha':head,'backend':'native_git','mode':'DETACHED_REVIEW_PREPARATION','environment_id':'cloud-continuation-a1','check_suite_fingerprint':op._hash(proof),'environment_fingerprint':op._hash({'source_id':rid}),'check_plan_digest':op._hash({'candidate_ref':candidate_ref,'source_must_stay':proof['base'],'candidate':head})}
intent=op.prepare(binding,req['attempt_id']+'-ordered-review-journal-publication',req['lease_source_ref'],now());store=GitDocumentStore(repo,'origin','refs/heads/cdc/adopt2121-'+name+'-ordered-review-journal-operation-20261008',rid);ir,old=store.read();assert ir is None or (old==intent or (old.get('state')=='prepared' and old.get('binding')==intent['binding'] and old.get('attempt_id')==intent['attempt_id'])),'unknown submission never replay';intent=old if ir is not None else intent;ir=store.compare_and_swap(None,intent) if ir is None else ir;rr,d=store.read();assert rr==ir;read_receipt=op.verify_readback(intent,d,'git:'+ir+':document.json',now());intent=op.transition(intent,'submitting',now(),receipt=read_receipt);ir=store.compare_and_swap(ir,intent)
s=importlib.util.spec_from_file_location('bu','/workspace/work/normalize2121-adapter/budget-update.py');bu=importlib.util.module_from_spec(s);s.loader.exec_module(bu);wake='cloud-adopt2121-20261008';e={'type':'reserve','event_id':'adopt2121-'+name+'-ordered-review-journal-publication','task_id':'cdc-parallel-maintenance','wake_id':wake,'at_utc':now(),'kind':'tool_call','operation_key':intent['operation_key'],'attempt_id':intent['attempt_id'],'scope':'detached-candidate-publication/'+name,'recovery_ref':None,'cost':{'tool_calls':1,'tokens':None,'elapsed_seconds':None}};br=bu.update([e],wake,str(root/'ordered-review-journal-budget.json'))
lr,l=ls.read();l=v2.set_guard(l,h['owner_id'],h['generation'],h['invocation_id'],now(),intent,'git:'+ir+':document.json');lr=ls.compare_and_swap(lr,l)
assert git('ls-remote','origin',req['lease_source_ref']).split()[0]==proof['base'] and not git('ls-remote','origin',candidate_ref)
live=bridge.observe({'schema':'managed-host-observe/v1','handle_root':req['handle_root'],'handle_id':h['handle_id']});assert live['lease_owned'] and live['runtime_status']=='awaiting_release'
assert subprocess.check_output(['git','ls-remote','origin','refs/heads/cdc/parallel-maintenance-budget-20261007'],cwd='/workspace/g-cdc',text=True).split()[0]==br
lr,l=ls.read();claim=v2.claim_submission(ls,lr,req['lease_repository'],req['lease_source_ref'],h['owner_id'],h['generation'],h['invocation_id'],now(),intent_digest=op._hash(intent));(root/'ordered-review-journal-claim.json').write_text(json.dumps(claim,indent=2)+'\n')
argv=['push','origin',head+':'+candidate_ref];output=git(*argv);readback=git('ls-remote','origin',candidate_ref).split()[0];assert readback==head;assert git('ls-remote','origin',req['lease_source_ref']).split()[0]==proof['base']
task={'task_id':head,'task_url':'https://github.com/'+req['lease_repository']+'/tree/'+candidate_ref.removeprefix('refs/heads/'),'operation_key':intent['operation_key'],'attempt_id':intent['attempt_id'],'binding':intent['binding'],'state':'terminal','conclusion':'succeeded','evidence_refs':['git:'+head]};obs={'schema':'operation-observation/v1','operation_key':intent['operation_key'],'lookup_complete':True,'observed_at_utc':now(),'tasks':[task]};lr,l=ls.read();lr=ls.compare_and_swap(lr,v2.clear_guard(l,h['owner_id'],h['generation'],h['invocation_id'],now(),obs,'git:'+head));ir,old=store.read();store.compare_and_swap(ir,op.transition(old,'terminal',now(),task=task))
receipt={'candidate_ref':candidate_ref,'candidate':head,'native_argv':['git',*argv],'exit_code':0,'readback':readback,'source_base_unchanged':proof['base'],'claim':claim,'guard_resolution_revision':lr,'at_utc':now()};(root/'ordered-review-journal-publication.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
